version: '3'

services:
  app:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    working_dir: /app
    command: './gradlew bootRun'
    environment:
            - GRADLE_USER_HOME=cache